[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "jasons-kickstart-compiler"
version = "0.0.0"
requires-python = ">=3.7"

[project.urls]
Homepage = "https://jasonyundt.website/gitweb?p=jasons-kickstart-compiler;a=summary"
